version: "3.7"
services:
  jnb:
    image: mecab-base-notebook
    container_name: mecab-notebook
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "889:8888"
    volumes:
      - ./work:/home/jovyan/work